CREATE TABLE "enlaces_externos" (
  "id_enlace"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "categoria"          VARCHAR(50)  NOT NULL,
  "nombre_entidad"     VARCHAR(200) NOT NULL,
  "url"                VARCHAR(500),
  "correo_contacto"    VARCHAR(150),
  "telefono_contacto"  VARCHAR(30),
  "ciudad"             VARCHAR(100),
  "requiere_login"     BOOLEAN DEFAULT FALSE,
  "notas"              TEXT,
  "activo"             BOOLEAN DEFAULT TRUE NOT NULL,
  "fecha_creacion"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "creado_por_id"      BIGINT
);

CREATE INDEX ON "enlaces_externos" ("categoria");
CREATE INDEX ON "enlaces_externos" ("nombre_entidad");
