-- Solicitudes de reversión: el GESTOR pide revertir una solicitud CANCELADA,
-- y un ADMIN_POLYGRAPH debe aprobarla o rechazarla antes de que el estado cambie.
CREATE TABLE "reversiones_solicitud" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" INTEGER NOT NULL,
  "estado_deseado" VARCHAR(40) NOT NULL,
  "motivo" TEXT NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  "id_solicitado_por" BIGINT NOT NULL,
  "fecha_solicitud" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "id_revisado_por" BIGINT,
  "fecha_revision" TIMESTAMP,
  "comentario_revision" TEXT
);

CREATE INDEX ON "reversiones_solicitud" ("id_servicio");
CREATE INDEX ON "reversiones_solicitud" ("estado");

ALTER TABLE "reversiones_solicitud" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reversiones_solicitud" ADD FOREIGN KEY ("id_solicitado_por") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "reversiones_solicitud" ADD FOREIGN KEY ("id_revisado_por") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
