-- Asignación de un subproceso (tipo_progreso) de un servicio concreto a un usuario ejecutor.
CREATE TABLE servicio_subprocesos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_servicio         INTEGER NOT NULL REFERENCES servicios (id_servicio) ON DELETE CASCADE,
    id_tipo_progreso    INTEGER NOT NULL REFERENCES tipos_progreso (id_tipo_progreso),
    id_usuario_asignado BIGINT REFERENCES usuarios (id_usuario),
    estado              VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_programada    TIMESTAMP,
    fecha_asignacion    TIMESTAMP,
    fecha_completado    TIMESTAMP,
    observaciones       TEXT,
    fecha_creacion      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_servicio, id_tipo_progreso)
);

CREATE INDEX ON servicio_subprocesos (id_usuario_asignado);
CREATE INDEX ON servicio_subprocesos (fecha_programada);
