-- Mensajería temporal entre un cliente y su gestor asignado.
-- Los mensajes expiran (fecha_expiracion) y se purgan automáticamente vía tarea
-- programada (MensajeService.limpiarExpirados) — no es un historial permanente de auditoría.
CREATE TABLE mensajes_cliente_gestor (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          INTEGER NOT NULL REFERENCES clientes (id_cliente) ON DELETE CASCADE,
    id_usuario_emisor   BIGINT NOT NULL REFERENCES usuarios (id_usuario),
    origen              VARCHAR(10) NOT NULL,
    mensaje             TEXT NOT NULL,
    fecha_envio         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion    TIMESTAMP NOT NULL,
    leido               BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX ON mensajes_cliente_gestor (id_cliente, fecha_envio);
CREATE INDEX ON mensajes_cliente_gestor (fecha_expiracion);
