-- Carrito de compras + checkout Wompi para clientes PREPAGO: el cliente compra
-- N unidades de cada tipo de proceso (bolsa de servicios prepago) y las consume
-- después al crear solicitudes. No existe tabla de "carrito abierto": el carrito
-- vive en el frontend (localStorage) y solo se persiste al crear la orden de compra.

CREATE TABLE "ordenes_compra" (
  "id_orden_compra" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" INTEGER NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "referencia" VARCHAR(50) NOT NULL UNIQUE,
  "monto_total" NUMERIC(15,2) NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  "modo_simulado" BOOLEAN NOT NULL DEFAULT FALSE,
  "id_transaccion_pasarela" VARCHAR(100),
  "metodo_pago" VARCHAR(50),
  "url_checkout" TEXT,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_actualizacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_expiracion" TIMESTAMP
);

CREATE INDEX ON "ordenes_compra" ("id_cliente");
CREATE INDEX ON "ordenes_compra" ("estado");

CREATE TABLE "orden_compra_items" (
  "id_item" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_orden_compra" BIGINT NOT NULL,
  "id_proceso" INTEGER NOT NULL,
  "cantidad" INTEGER NOT NULL CHECK ("cantidad" > 0),
  "valor_unitario" NUMERIC(15,2) NOT NULL,
  "subtotal" NUMERIC(15,2) NOT NULL
);

CREATE INDEX ON "orden_compra_items" ("id_orden_compra");

CREATE TABLE "saldos_servicio_cliente" (
  "id_saldo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" INTEGER NOT NULL,
  "id_proceso" INTEGER NOT NULL,
  "cantidad_comprada" INTEGER NOT NULL DEFAULT 0,
  "cantidad_consumida" INTEGER NOT NULL DEFAULT 0,
  "cantidad_disponible" INTEGER NOT NULL DEFAULT 0,
  "fecha_actualizacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("id_cliente", "id_proceso")
);

CREATE TABLE "transacciones_pago" (
  "id_transaccion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_orden_compra" BIGINT NOT NULL,
  "estado" VARCHAR(20) NOT NULL,
  "id_transaccion_wompi" VARCHAR(100),
  "origen" VARCHAR(20) NOT NULL,
  "payload_raw" TEXT,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON "transacciones_pago" ("id_orden_compra");
CREATE UNIQUE INDEX "uq_transacciones_pago_id_wompi" ON "transacciones_pago" ("id_transaccion_wompi") WHERE "id_transaccion_wompi" IS NOT NULL;

ALTER TABLE "ordenes_compra" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ordenes_compra" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_compra_items" ADD FOREIGN KEY ("id_orden_compra") REFERENCES "ordenes_compra" ("id_orden_compra") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "orden_compra_items" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldos_servicio_cliente" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "saldos_servicio_cliente" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacciones_pago" ADD FOREIGN KEY ("id_orden_compra") REFERENCES "ordenes_compra" ("id_orden_compra") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
