-- Precios por volumen: un proceso puede tener tramos de descuento por cantidad comprada
-- (ej. comprar 20 unidades cuesta menos por unidad que comprar 1). Si la cantidad no alcanza
-- ningún tramo, se usa el precio base de procesos.valor. Se aplica solo en la compra de saldo
-- prepago (módulo Comprar Servicios), calculado siempre en el backend al crear la orden — nunca
-- se confía en un precio que mande el cliente.
CREATE TABLE "tramos_precio_proceso" (
  "id_tramo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_proceso" INTEGER NOT NULL,
  "cantidad_minima" INTEGER NOT NULL CHECK ("cantidad_minima" >= 2),
  "valor_unitario" NUMERIC(15,2) NOT NULL,
  UNIQUE ("id_proceso", "cantidad_minima")
);

CREATE INDEX ON "tramos_precio_proceso" ("id_proceso");

ALTER TABLE "tramos_precio_proceso" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
