-- Paquetes: combos de varios subprocesos vendidos como una sola cosa (ver V128 para la tabla
-- de subprocesos del paquete — tipos_progreso, no procesos). FIJO = subprocesos fijos definidos
-- por el admin. PERSONALIZABLE = obligatorios + un pool de opcionales que el cliente elige
-- (entre seleccion_minima y seleccion_maxima).

CREATE TABLE "paquetes" (
  "id_paquete" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(150) NOT NULL,
  "descripcion" TEXT,
  "tipo_paquete" VARCHAR(20) NOT NULL,
  "seleccion_minima" INTEGER,
  "seleccion_maxima" INTEGER,
  "activo" BOOLEAN NOT NULL DEFAULT TRUE,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Traza opcional: un ítem de orden puede venir de comprar un paquete.
ALTER TABLE "orden_compra_items" ADD COLUMN "id_paquete" BIGINT;
ALTER TABLE "orden_compra_items" ADD FOREIGN KEY ("id_paquete") REFERENCES "paquetes" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;
