-- Descuentos dinámicos: % o monto fijo, con o sin código (cupón), con o sin vigencia,
-- aplicables a todo el catálogo, una categoría, un proceso puntual o un paquete.

CREATE TABLE "descuentos" (
  "id_descuento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(150) NOT NULL,
  "codigo" VARCHAR(50) UNIQUE,
  "tipo" VARCHAR(20) NOT NULL,
  "valor" NUMERIC(15,2) NOT NULL,
  "alcance" VARCHAR(20) NOT NULL,
  "id_clasificacion" INTEGER,
  "id_proceso" INTEGER,
  "id_paquete" BIGINT,
  "monto_maximo_descuento" NUMERIC(15,2),
  "fecha_inicio" TIMESTAMP,
  "fecha_fin" TIMESTAMP,
  "activo" BOOLEAN NOT NULL DEFAULT TRUE,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON "descuentos" ("codigo");
CREATE INDEX ON "descuentos" ("activo");
CREATE INDEX ON "descuentos" ("alcance");

ALTER TABLE "descuentos" ADD FOREIGN KEY ("id_clasificacion") REFERENCES "clasificaciones_proceso" ("id_clasificacion") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "descuentos" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "descuentos" ADD FOREIGN KEY ("id_paquete") REFERENCES "paquetes" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;
