-- Corrige V126: los "bloques" de un paquete personalizable deben ser subprocesos
-- (tipos_progreso) — igual que un Proceso se arma de subprocesos vía proceso_tipo_progreso —
-- no procesos completos del catálogo. Se reemplaza "paquete_procesos" (id_proceso) por
-- "paquete_subprocesos" (id_tipo_progreso). No había datos reales en la tabla vieja
-- (funcionalidad recién creada, nunca usada por un cliente), por eso se elimina directo.

DROP TABLE IF EXISTS "paquete_procesos";

CREATE TABLE "paquete_subprocesos" (
  "id_paquete_subproceso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_paquete" BIGINT NOT NULL,
  "id_tipo_progreso" INTEGER NOT NULL,
  "obligatorio" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX ON "paquete_subprocesos" ("id_paquete");
ALTER TABLE "paquete_subprocesos" ADD FOREIGN KEY ("id_paquete") REFERENCES "paquetes" ("id_paquete") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "paquete_subprocesos" ADD FOREIGN KEY ("id_tipo_progreso") REFERENCES "tipos_progreso" ("id_tipo_progreso") DEFERRABLE INITIALLY IMMEDIATE;
