-- Tabla de clasificaciones de proceso (reemplaza enum fijo ClasificacionProceso)
CREATE TABLE "clasificaciones_proceso" (
    "id_clasificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "codigo"      VARCHAR(5)   UNIQUE NOT NULL,
    "nombre"      VARCHAR(100) NOT NULL,
    "descripcion" TEXT,
    "activo"      BOOLEAN DEFAULT TRUE
);

-- Clasificaciones iniciales (equivalentes al enum anterior)
INSERT INTO "clasificaciones_proceso" ("codigo", "nombre", "descripcion") VALUES
    ('A', 'Servicios y Estudios de Hoja de Vida', 'Validación laboral, académica, personal y financiera'),
    ('B', 'Pruebas de Confiabilidad',             'Poligrafías y pruebas de detección de engaño'),
    ('C', 'Estudios de Seguridad',                'Estudios integrales de confiabilidad y seguridad'),
    ('D', 'Otros',                                'Otros servicios especializados');

-- Agregar FK a procesos apuntando a la nueva tabla
ALTER TABLE "procesos" ADD COLUMN "id_clasificacion" INTEGER;

UPDATE "procesos" p
SET "id_clasificacion" = c."id_clasificacion"
FROM "clasificaciones_proceso" c
WHERE p."clasificacion" = c."codigo";

ALTER TABLE "procesos" ALTER COLUMN "id_clasificacion" SET NOT NULL;
ALTER TABLE "procesos" ADD FOREIGN KEY ("id_clasificacion") REFERENCES "clasificaciones_proceso" ("id_clasificacion");

-- Eliminar columna antigua
ALTER TABLE "procesos" DROP COLUMN "clasificacion";

-- Columna valor en procesos y tipos_progreso
ALTER TABLE "procesos"       ADD COLUMN "valor" DECIMAL(15,2);
ALTER TABLE "tipos_progreso" ADD COLUMN "valor" DECIMAL(15,2);
