-- Un proceso puede marcarse "aplica precio por ciudad" (ej. visitas domiciliarias) y tener un
-- precio distinto por nivel logístico de ciudad (PRINCIPAL / INTERMEDIA / MUNICIPIO_SECUNDARIO),
-- en vez de un único valor base. Si no aplica, se sigue usando procesos.valor como hoy.
ALTER TABLE "procesos" ADD COLUMN "aplica_precio_ciudad" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE "precios_ciudad_proceso" (
  "id_precio_ciudad" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_proceso" INTEGER NOT NULL,
  "nivel_ciudad" VARCHAR(30) NOT NULL,
  "valor" NUMERIC(15,2) NOT NULL,
  UNIQUE ("id_proceso", "nivel_ciudad")
);

CREATE INDEX ON "precios_ciudad_proceso" ("id_proceso");

ALTER TABLE "precios_ciudad_proceso" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
