CREATE TABLE "ciudades" (
  "id_ciudad" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_ciudad" varchar(150) NOT NULL,
  "departamento" varchar(100) NOT NULL,
  "codigo_dane_ciudad" varchar(10),
  "codigo_dane_depto" varchar(2)
);

CREATE TABLE "clientes" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_cliente" varchar(10) NOT NULL,
  "tipo_persona" varchar(10) NOT NULL,
  "nit" varchar(20) UNIQUE,
  "dv" VARCHAR(1),
  "razon_social" varchar(200),
  "nombre_comercial" varchar(200),
  "representante_legal" varchar(150),
  "nombre" varchar(100),
  "apellido" varchar(100),
  "email_principal" varchar(150) UNIQUE NOT NULL,
  "telefono" varchar(20),
  "id_ciudad" integer,
  "direccion" text,
  "fecha_registro" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "estado" varchar(20) DEFAULT 'ACTIVO'
);

CREATE TABLE "clientes_pospago" (
  "id_cliente" integer PRIMARY KEY,
  "limite_credito" decimal(15,2) DEFAULT 0,
  "credito_disponible" decimal(15,2) DEFAULT 0,
  "estado_mora" varchar(20) DEFAULT 'NORMAL',
  "dias_mora" integer DEFAULT 0,
  "fecha_ultima_factura" date,
  "ultima_revision_credito" date,
  "requiere_aprobacion" boolean DEFAULT true
);

CREATE TABLE "soportes_clientes" (
  "id_soporte" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "tipo_soporte" varchar(100) NOT NULL,
  "fecha_solicitud" date DEFAULT (CURRENT_DATE),
  "fecha_vencimiento" date,
  "estado" varchar(50) DEFAULT 'pendiente',
  "archivo_adjunto" varchar(255),
  "fecha_entrega" date,
  "observaciones" text,
  "usuario_registra" varchar(50) NOT NULL,
  "validado_por" varchar(50),
  "fecha_validacion" timestamp
);

CREATE TABLE "candidatos" (
  "id_candidato" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cedula" varchar(20) UNIQUE NOT NULL,
  "tipo_documento" varchar(20) NOT NULL,
  "nombres" varchar(200) NOT NULL,
  "apellidos" varchar(200) NOT NULL,
  "lugar_nacimiento" varchar(200),
  "fecha_nacimiento" date,
  "fecha_expedicion" date,
  "id_ciudad_nacimiento" integer,
  "id_ciudad_residencia" integer,
  "direccion_residencia" text,
  "barrio_residencia" varchar(100),
  "telefono_fijo" varchar(20),
  "celular" varchar(20),
  "email_principal" varchar(150),
  "sector" varchar(50),
  "estrato" varchar(1),
  "libreta_militar" varchar(20),
  "rut" varchar(20)
);

CREATE TABLE "empleados" (
  "id_empleado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_empleado" varchar(20) NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100),
  "telefono" varchar(20),
  "email" varchar(150),
  "sala_encargada" varchar(100),
  "zonas_visita" varchar(200),
  "activo" boolean DEFAULT true,
  "fecha_ingreso" date DEFAULT (CURRENT_DATE)
);

CREATE TABLE "procesos" (
  "id_proceso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_proceso" varchar(100) UNIQUE NOT NULL,
  "descripcion" text,
  "activo" boolean DEFAULT true
);

CREATE TABLE "tipos_progreso" (
  "id_tipo_progreso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_progreso" varchar(100) NOT NULL,
  "descripcion" text,
  "orden" integer DEFAULT 0,
  "activo" boolean DEFAULT true
);

CREATE TABLE "procesos_tipos_progreso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_proceso" integer NOT NULL,
  "id_tipo_progreso" integer NOT NULL,
  "habilitado" boolean DEFAULT true,
  "orden_en_proceso" integer DEFAULT 0,
  "obligatorio" boolean DEFAULT true
);

CREATE TABLE "servicios" (
  "id_servicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "id_candidato" bigint,
  "fecha_solicitud" date DEFAULT (CURRENT_DATE),
  "hora_solicitud" time,
  "id_proceso" integer NOT NULL,
  "estado" varchar(40) DEFAULT 'PENDIENTE',
  "resultado" varchar(100),
  "observacion" text,
  "fecha_entrega_estudio" date,
  "fecha_de_envio" date
);

CREATE TABLE "verificaciones_referencias" (
  "id_verificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_verificacion" date DEFAULT (CURRENT_DATE),
  "observaciones_generales" text
);

CREATE TABLE "referencias_laborales" (
  "id_referencia_laboral" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion" integer NOT NULL,
  "empresa" varchar(200),
  "nit" varchar(20),
  "ciudad" varchar(100),
  "direccion" text,
  "telefono_empresa" varchar(30),
  "cargo" varchar(150),
  "area_departamento" varchar(100),
  "tipo_contrato" varchar(50),
  "modalidad" varchar(30),
  "fecha_ingreso" date,
  "fecha_retiro" date,
  "labora_actualmente" boolean,
  "salario_devengado" decimal(12,2),
  "motivo_retiro" varchar(200),
  "recibio_llamados_atencion" boolean,
  "observaciones" text,
  "jefe_nombre" varchar(150),
  "jefe_cargo" varchar(100),
  "jefe_telefono" varchar(30),
  "jefe_email" varchar(150),
  "trabajo_temporal" boolean,
  "empresa_temporal" varchar(200),
  "telefono_temporal" varchar(30),
  "contacto_temporal" varchar(150),
  "certificado_laboral" varchar(255)
);

CREATE TABLE "periodos_inactividad_laboral" (
  "id_periodo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion" integer NOT NULL,
  "fecha_inicio" date,
  "fecha_fin" date,
  "dias_inactivo" integer,
  "actividad_principal" varchar(100),
  "descripcion" text,
  "adjunto_certificacion" varchar(255),
  "requiere_investigacion" boolean DEFAULT false
);

CREATE TABLE "referencias_personales" (
  "id_referencia_personal" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion" integer NOT NULL,
  "nombre" varchar(150),
  "parentesco" varchar(50),
  "tiempo_conocimiento" varchar(100),
  "ultima_comunicacion" varchar(150),
  "sabe_laborando" varchar(100),
  "sabe_donde_trabajado" varchar(200),
  "concepto" text
);

CREATE TABLE "verificaciones_academicas" (
  "id_verificacion_academica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_verificacion" date,
  "observaciones_generales" text
);

CREATE TABLE "referencias_academicas" (
  "id_referencia_academica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_academica" integer NOT NULL,
  "nivel" varchar(50),
  "tipo_estudio" varchar(50),
  "institucion" varchar(200),
  "pais" varchar(100),
  "departamento" varchar(100),
  "ciudad" varchar(100),
  "sede" varchar(100),
  "direccion" text,
  "presento_icfes" boolean,
  "ano_icfes" integer,
  "numero_icfes" varchar(50),
  "estado" varchar(30),
  "titulo_obtenido" varchar(200),
  "fecha_graduacion" date,
  "observacion" text,
  "acta_diploma" varchar(255)
);

CREATE TABLE "verificaciones_financieras" (
  "id_verificacion_financiera" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_verificacion" date DEFAULT (CURRENT_DATE),
  "estado_documento" varchar(50),
  "rango_edad" varchar(20),
  "concepto_endeudamiento" text,
  "cuota_mensual_obligaciones" decimal(12,2),
  "ingreso_estimado" decimal(12,2),
  "porcentaje_utilizacion" decimal(5,2),
  "concepto_final" text,
  "score_final" integer,
  "probabilidad_cumplimiento" varchar(50),
  "observaciones_generales" text
);

CREATE TABLE "obligaciones_financieras" (
  "id_obligacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_financiera" integer NOT NULL,
  "sector" varchar(50),
  "obligaciones_vigentes" integer DEFAULT 0,
  "obligaciones_extinguidas" integer DEFAULT 0,
  "obligaciones_codeudor" integer DEFAULT 0,
  "saldo_actual" decimal(12,2) DEFAULT 0,
  "valor_cuota" decimal(12,2) DEFAULT 0,
  "valor_mora" decimal(12,2) DEFAULT 0
);

CREATE TABLE "verificaciones_antecedentes_legales" (
  "id_verificacion_legal" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_verificacion" date DEFAULT (CURRENT_DATE),
  "observaciones_generales" text
);

CREATE TABLE "antecedentes_consultados" (
  "id_consulta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_legal" integer NOT NULL,
  "categoria" varchar(100),
  "fuente" varchar(150),
  "hallazgo" boolean DEFAULT false,
  "no_hallazgo" boolean DEFAULT true,
  "observacion" text,
  "anexo" varchar(255)
);

CREATE TABLE "simit" (
  "id_simit" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_legal" integer NOT NULL,
  "multas" varchar(100),
  "comparendos" varchar(100),
  "acuerdos_pago" varchar(100),
  "inmovilizaciones" varchar(100),
  "observacion" text,
  "anexo" varchar(255)
);

CREATE TABLE "simur" (
  "id_simur" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_legal" integer NOT NULL,
  "comparendo" varchar(100),
  "placa" varchar(50),
  "fecha_infraccion" date,
  "observacion" text,
  "anexo" varchar(255)
);

CREATE TABLE "runt" (
  "id_runt" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_verificacion_legal" integer NOT NULL,
  "categoria" varchar(100),
  "estado" varchar(100),
  "fecha_vencimiento" varchar(100),
  "observacion" text,
  "anexo" varchar(255)
);

CREATE TABLE "visitas_domiciliarias" (
  "id_visita" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_recibo_orden" date,
  "fecha_visita" date,
  "id_ciudad" integer,
  "observaciones_generales" text,
  "cargo" varchar(150),
  "salario_devengar" decimal(12,2),
  "quien_atiende_visita" varchar(150),
  "parentesco_quien_atiende" varchar(50),
  "como_llego_hoja_vida" text,
  "puntaje_total_visita" decimal(5,2),
  "concepto_final_visita" varchar(30),
  "recomendacion" varchar(20),
  "tipo_vivienda" varchar(50),
  "estrato" varchar(1),
  "ubicacion_barrio" varchar(150),
  "estado_calles" text,
  "zonas_verdes" varchar(100),
  "locales_comerciales" text,
  "vias_acceso" text,
  "problematicas_sociales" text,
  "fecha_registro" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "familia_visita" (
  "id_familiar" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "nombre" varchar(150),
  "parentesco" varchar(50),
  "edad" integer,
  "estado_civil" varchar(50),
  "ocupacion" varchar(150),
  "entidad" varchar(150),
  "nivel_educativo" varchar(100)
);

CREATE TABLE "academica_visita" (
  "id_academica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "tipo_estudio" varchar(50),
  "institucion" varchar(200),
  "titulo" varchar(200),
  "ano_finalizacion" integer,
  "observaciones_academicas" text
);

CREATE TABLE "vivienda_visita" (
  "id_vivienda" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "tenencia" varchar(50),
  "tamano" varchar(50),
  "estado" varchar(50),
  "tiempo_residencia" varchar(100),
  "dotacion" varchar(50),
  "organizacion_limpieza" varchar(50),
  "aspecto_fisico" varchar(50),
  "servicios_publicos" varchar(50),
  "habitaciones" integer,
  "banos" integer,
  "cocina" integer,
  "salas" integer,
  "comedor" integer,
  "patio_ropa" integer,
  "estudio" integer,
  "balcon" integer,
  "electrodomesticos" text,
  "televisores" integer,
  "nevera" integer,
  "computadores" integer,
  "lavadora" integer,
  "secadora" integer,
  "microondas" integer,
  "equipo_sonido" integer,
  "chimenea" integer,
  "teatro_casa" integer,
  "estado_infraestructura" varchar(50),
  "estado_enseres" varchar(50),
  "observaciones_vivienda" text
);

CREATE TABLE "concepto_dinamica_familiar" (
  "id_concepto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "aprendizaje_continuo" integer,
  "liderazgo" integer,
  "proyecciones" integer,
  "recursividad" integer,
  "compromiso_familiar" integer,
  "trabajo_equipo" integer,
  "canales_comunicacion" integer,
  "manejo_autoridad" integer,
  "manejo_conflictos" integer,
  "negociacion_conciliacion" integer,
  "exposicion_situaciones" integer,
  "tolerancia_frustracion" integer,
  "total_puntos" integer,
  "promedio_total" decimal(5,2),
  "concepto_familiar" text,
  "orientada_logro" text,
  "orientada_servicio" text,
  "afrontamiento_dificultades" text
);

CREATE TABLE "concepto_habitacional" (
  "id_concepto_hab" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "estado_estructura" integer,
  "condiciones_entorno" integer,
  "espacio_numero_habitantes" integer,
  "total_puntos" integer,
  "promedio_total" decimal(5,2),
  "concepto_final" varchar(30)
);

CREATE TABLE "ingresos_familia_visita" (
  "id_ingreso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "integrante" varchar(150),
  "concepto" varchar(100),
  "monto" decimal(12,2),
  "mejor_ingreso" varchar(100)
);

CREATE TABLE "egresos_familia_visita" (
  "id_egreso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "integrante" varchar(150),
  "concepto" varchar(100),
  "monto" decimal(12,2),
  "asume_candidato" varchar(100)
);

CREATE TABLE "deudas_candidato_visita" (
  "id_deuda" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "tiene_deudas_activas" boolean,
  "observaciones_economicas" text,
  "obligacion" varchar(100),
  "entidad" varchar(150),
  "valor_credito" decimal(12,2),
  "numero_cuotas" integer,
  "saldo_pendiente" decimal(12,2),
  "valor_cuota_mensual" decimal(12,2),
  "mora_dias" integer
);

CREATE TABLE "protocolo_seguridad_visita" (
  "id_protocolo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "preguntas" text,
  "si_no" boolean,
  "observaciones_protocolo" text
);

CREATE TABLE "registro_fotografico_visita" (
  "id_foto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "tipo_foto" varchar(50),
  "archivo" varchar(255)
);

CREATE TABLE "decadactilar_visita" (
  "id_decadactilar" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "mano" varchar(20),
  "dedo" varchar(20),
  "archivo_imagen" varchar(255)
);

CREATE TABLE "patrimonio_familiar_visita" (
  "id_patrimonio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "tipo_inmueble" varchar(100),
  "ubicacion_marca" varchar(200),
  "valor" decimal(15,2),
  "observaciones" text
);

CREATE TABLE "economia_candidato_visita" (
  "id_economia_candidato" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "reportado_central_riesgo_actual" boolean,
  "reportado_central_riesgo_historico" boolean,
  "observaciones_riesgo" text
);

CREATE TABLE "concepto_economico_visita" (
  "id_concepto_economico" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "equilibrio_economico" integer,
  "organizacion_presupuesto" integer,
  "endeudamiento_familiar" integer,
  "total_puntos" integer,
  "promedio_total" decimal(5,2),
  "concepto_final" varchar(30),
  "observaciones" text
);

CREATE TABLE "estado_salud" (
  "id_protocolo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_visita" integer NOT NULL,
  "preguntas" text,
  "observaciones_protocolo" text
);

CREATE TABLE "informes_poligrafia" (
  "id_informe_poligrafia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "fecha_examen" date,
  "tipo_examen" varchar(50),
  "ciudad_examen" varchar(100),
  "cargo" varchar(150),
  "poligrafo_anterior" varchar(100),
  "estado_salud_general" text,
  "observaciones_generales" text,
  "conclusion_final" varchar(100),
  "grafico_resultado" text,
  "puntaje_total" decimal(5,2),
  "fecha_registro" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "historia_medica_poligrafia" (
  "id_historia_medica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "estado_salud_fisica" text,
  "estado_salud_mental" text,
  "tratamiento_medico" text,
  "cirugias" text,
  "problemas_respiratorios" boolean,
  "problemas_cardiovasculares" boolean,
  "consumo_ultimas_24h" text,
  "pensamientos_suicidas" boolean,
  "pensamientos_homicidas" boolean,
  "antecedentes_familiares" text,
  "observaciones_medicas" text
);

CREATE TABLE "historia_familiar_poligrafia" (
  "id_historia_familiar" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "nombre_pareja" varchar(150),
  "edad_pareja" integer,
  "tiempo_relacion" varchar(100),
  "tiempo_conviviendo" varchar(100),
  "calidad_relacion" text,
  "vive_con_pareja" boolean,
  "padre_fallecido" boolean,
  "causa_fallecimiento_padre" text,
  "madre_nombre" varchar(150),
  "madre_edad" integer,
  "madre_ocupacion" varchar(150),
  "hermano_nombre" varchar(150),
  "hermano_edad" integer,
  "observaciones_familia" text
);

CREATE TABLE "educacion_poligrafia" (
  "id_educacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "observaciones_educacion" text
);

CREATE TABLE "historia_financiera_poligrafia" (
  "id_historia_financiera" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "salario_actual" decimal(12,2),
  "gastos_mensuales" decimal(12,2),
  "tarjetas_credito" text,
  "deudas_informales" boolean,
  "reportado_central_riesgo" boolean,
  "patrimonio" text,
  "observaciones_financieras" text
);

CREATE TABLE "consumo_alcohol_poligrafia" (
  "id_consumo_alcohol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "frecuencia" varchar(100),
  "cantidad_consumo" text,
  "tipo_bebida" varchar(100),
  "embriagarse" boolean,
  "rinas_alcohol" boolean,
  "problemas_familiares" boolean,
  "problemas_laborales" boolean,
  "ir_trabajar_ebrio" boolean,
  "observaciones_alcohol" text
);

CREATE TABLE "consumo_drogas_poligrafia" (
  "id_consumo_drogas" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "consumo_marihuana" boolean,
  "frecuencia_drogas" text,
  "venta_transporte_drogas" boolean,
  "relacion_narcotraficantes" boolean,
  "observaciones_drogas" text
);

CREATE TABLE "antecedentes_poligrafia" (
  "id_antecedente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "antecedentes_judiciales" boolean,
  "procesos_civiles" boolean,
  "victima_hurto" boolean,
  "observaciones_antecedentes" text
);

CREATE TABLE "vinculos_poligrafia" (
  "id_vinculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "familiar_presos" boolean,
  "relacion_grupos_al_margen" boolean,
  "observaciones_vinculos" text
);

CREATE TABLE "planes_infiltracion" (
  "id_plan" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "como_llego_hoja_vida" text,
  "conocidos_en_empresa" boolean,
  "intencion_filtrar_info" boolean,
  "observaciones_planes" text
);

CREATE TABLE "experiencia_laboral_poligrafia" (
  "id_experiencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "empresa" varchar(200),
  "cargo" varchar(150),
  "fecha_ingreso" date,
  "fecha_retiro" date,
  "salario" decimal(12,2),
  "tipo_contrato" varchar(50),
  "motivo_retiro" text,
  "observaciones_laboral" text
);

CREATE TABLE "preguntas_antecedentes_laborales" (
  "id_pregunta_laboral" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "pregunta" text,
  "respuesta" boolean,
  "observacion_respuesta" text
);

CREATE TABLE "tecnica_poligrafica" (
  "id_tecnica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "poligrafista" varchar(150),
  "tecnica_utilizada" varchar(50),
  "equipo" varchar(100),
  "conclusion_tecnica" text
);

CREATE TABLE "preguntas_relevantes_poligrafia" (
  "id_pregunta_relevante" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "pregunta" text,
  "respuesta" varchar(10),
  "calificacion" integer
);

CREATE TABLE "autorizacion_poligrafia" (
  "id_autorizacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_informe_poligrafia" integer NOT NULL,
  "soporte" varchar(100),
  "documento_cargado" varchar(255)
);

CREATE TABLE "documentos" (
  "id_documento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "tipo_documento" varchar(100) NOT NULL,
  "nombre_archivo" varchar(255) NOT NULL,
  "ruta_archivo" varchar(255),
  "tamano_archivo" bigint,
  "fecha_carga" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "fecha_solicitud" date,
  "fecha_recibido" date,
  "descripcion" text,
  "comunicados" text,
  "estado_documento" varchar(50) DEFAULT 'PENDIENTE'
);

CREATE TABLE "informes_analisis_final" (
  "id_informe_final" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" integer NOT NULL,
  "id_candidato" bigint NOT NULL,
  "id_analista" integer NOT NULL,
  "fecha_informe" date DEFAULT (CURRENT_DATE),
  "concepto_poligrafia" text,
  "concepto_visita" text,
  "concepto_antecedentes_legales" text,
  "concepto_antecedentes_financieros" text,
  "concepto_academico" text,
  "concepto_laboral" text,
  "concepto_referencias_personales" text,
  "concepto_final_general" varchar(50) NOT NULL,
  "recomendacion" varchar(100),
  "observaciones_finales" text,
  "fecha_revision" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- Índices
CREATE INDEX ON "ciudades" ("departamento");
CREATE UNIQUE INDEX ON "clientes" ("nit");
CREATE UNIQUE INDEX ON "clientes" ("email_principal");
CREATE INDEX ON "clientes" ("tipo_cliente");
CREATE INDEX ON "clientes_pospago" ("estado_mora");
CREATE INDEX ON "soportes_clientes" ("id_cliente");
CREATE INDEX ON "soportes_clientes" ("estado");
CREATE UNIQUE INDEX ON "candidatos" ("cedula");
CREATE INDEX ON "candidatos" ("email_principal");
CREATE INDEX ON "servicios" ("id_cliente");
CREATE INDEX ON "servicios" ("id_candidato");
CREATE INDEX ON "servicios" ("estado");
CREATE UNIQUE INDEX ON "procesos_tipos_progreso" ("id_proceso", "id_tipo_progreso");
CREATE INDEX ON "patrimonio_familiar_visita" ("id_visita");
CREATE INDEX ON "economia_candidato_visita" ("id_visita");
CREATE INDEX ON "concepto_economico_visita" ("id_visita");
CREATE INDEX ON "documentos" ("id_servicio");
CREATE INDEX ON "documentos" ("tipo_documento");
CREATE INDEX ON "documentos" ("estado_documento");
CREATE INDEX ON "documentos" ("fecha_carga");
CREATE INDEX ON "informes_analisis_final" ("id_servicio");
CREATE INDEX ON "informes_analisis_final" ("id_candidato");
CREATE INDEX ON "informes_analisis_final" ("concepto_final_general");

-- Foreign keys
ALTER TABLE "clientes" ADD FOREIGN KEY ("id_ciudad") REFERENCES "ciudades" ("id_ciudad") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "clientes_pospago" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "soportes_clientes" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "candidatos" ADD FOREIGN KEY ("id_ciudad_nacimiento") REFERENCES "ciudades" ("id_ciudad") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "candidatos" ADD FOREIGN KEY ("id_ciudad_residencia") REFERENCES "ciudades" ("id_ciudad") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "servicios" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "servicios" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidatos" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "servicios" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "procesos_tipos_progreso" ADD FOREIGN KEY ("id_proceso") REFERENCES "procesos" ("id_proceso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "procesos_tipos_progreso" ADD FOREIGN KEY ("id_tipo_progreso") REFERENCES "tipos_progreso" ("id_tipo_progreso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_referencias" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_referencias" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "referencias_laborales" ADD FOREIGN KEY ("id_verificacion") REFERENCES "verificaciones_referencias" ("id_verificacion") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "periodos_inactividad_laboral" ADD FOREIGN KEY ("id_verificacion") REFERENCES "verificaciones_referencias" ("id_verificacion") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "referencias_personales" ADD FOREIGN KEY ("id_verificacion") REFERENCES "verificaciones_referencias" ("id_verificacion") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_academicas" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_academicas" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "referencias_academicas" ADD FOREIGN KEY ("id_verificacion_academica") REFERENCES "verificaciones_academicas" ("id_verificacion_academica") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_financieras" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_financieras" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "obligaciones_financieras" ADD FOREIGN KEY ("id_verificacion_financiera") REFERENCES "verificaciones_financieras" ("id_verificacion_financiera") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_antecedentes_legales" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "verificaciones_antecedentes_legales" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "antecedentes_consultados" ADD FOREIGN KEY ("id_verificacion_legal") REFERENCES "verificaciones_antecedentes_legales" ("id_verificacion_legal") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "simit" ADD FOREIGN KEY ("id_verificacion_legal") REFERENCES "verificaciones_antecedentes_legales" ("id_verificacion_legal") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "simur" ADD FOREIGN KEY ("id_verificacion_legal") REFERENCES "verificaciones_antecedentes_legales" ("id_verificacion_legal") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "runt" ADD FOREIGN KEY ("id_verificacion_legal") REFERENCES "verificaciones_antecedentes_legales" ("id_verificacion_legal") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "visitas_domiciliarias" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "visitas_domiciliarias" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "visitas_domiciliarias" ADD FOREIGN KEY ("id_ciudad") REFERENCES "ciudades" ("id_ciudad") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "familia_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "academica_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vivienda_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "concepto_dinamica_familiar" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "concepto_habitacional" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ingresos_familia_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "egresos_familia_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deudas_candidato_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "protocolo_seguridad_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "registro_fotografico_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "decadactilar_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "patrimonio_familiar_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "economia_candidato_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "concepto_economico_visita" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "estado_salud" ADD FOREIGN KEY ("id_visita") REFERENCES "visitas_domiciliarias" ("id_visita") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "informes_poligrafia" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "informes_poligrafia" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historia_medica_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historia_familiar_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "educacion_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historia_financiera_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "consumo_alcohol_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "consumo_drogas_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "antecedentes_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vinculos_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "planes_infiltracion" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "experiencia_laboral_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "preguntas_antecedentes_laborales" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tecnica_poligrafica" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "preguntas_relevantes_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "autorizacion_poligrafia" ADD FOREIGN KEY ("id_informe_poligrafia") REFERENCES "informes_poligrafia" ("id_informe_poligrafia") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "documentos" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "informes_analisis_final" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "informes_analisis_final" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidatos" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "informes_analisis_final" ADD FOREIGN KEY ("id_analista") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;
