-- Tabla de usuarios del sistema (todos los roles)
CREATE TABLE "usuarios" (
  "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "apellido" VARCHAR(100),
  "email" VARCHAR(150) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "rol" VARCHAR(30) NOT NULL,
  "activo" BOOLEAN DEFAULT TRUE NOT NULL,
  "requiere_2fa" BOOLEAN DEFAULT FALSE,
  "secreto_2fa" VARCHAR(255),
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ultimo_acceso" TIMESTAMP,
  "id_empleado" INTEGER,
  "id_cliente" INTEGER
);

-- Tabla de tokens refresh JWT
CREATE TABLE "tokens_refresh" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "token" VARCHAR(500) UNIQUE NOT NULL,
  "fecha_expiracion" TIMESTAMP NOT NULL,
  "revocado" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Links temporales para que evaluados carguen su hoja de vida (expira 36h)
CREATE TABLE "links_candidato" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" INTEGER NOT NULL,
  "token" VARCHAR(200) UNIQUE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "fecha_expiracion" TIMESTAMP NOT NULL,
  "usado" BOOLEAN DEFAULT FALSE NOT NULL
);

-- Historial de cambios de estado del semáforo de servicio
CREATE TABLE "historial_estados_servicio" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" INTEGER NOT NULL,
  "estado_anterior" VARCHAR(40),
  "estado_nuevo" VARCHAR(40) NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "fecha_cambio" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "observacion" TEXT
);

-- Notificaciones internas para usuarios del sistema
CREATE TABLE "notificaciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "titulo" VARCHAR(200) NOT NULL,
  "mensaje" TEXT NOT NULL,
  "leida" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "fecha_lectura" TIMESTAMP,
  "referencia_tipo" VARCHAR(50),
  "referencia_id" BIGINT
);

-- Índices
CREATE INDEX ON "usuarios" ("email");
CREATE INDEX ON "usuarios" ("rol");
CREATE INDEX ON "usuarios" ("activo");
CREATE INDEX ON "tokens_refresh" ("id_usuario");
CREATE UNIQUE INDEX ON "tokens_refresh" ("token");
CREATE INDEX ON "links_candidato" ("id_servicio");
CREATE UNIQUE INDEX ON "links_candidato" ("token");
CREATE INDEX ON "historial_estados_servicio" ("id_servicio");
CREATE INDEX ON "historial_estados_servicio" ("id_usuario");
CREATE INDEX ON "historial_estados_servicio" ("fecha_cambio");
CREATE INDEX ON "notificaciones" ("id_usuario");
CREATE INDEX ON "notificaciones" ("leida");

-- Foreign keys
ALTER TABLE "tokens_refresh" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "links_candidato" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_estados_servicio" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_estados_servicio" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notificaciones" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
