-- Tabla de usuarios del sistema (todos los roles)
CREATE TABLE "usuarios" (
  "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "apellido" VARCHAR(100),
  "email" VARCHAR(150) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "rol" VARCHAR(30) NOT NULL,
  "activo" BOOLEAN DEFAULT TRUE NOT NULL,
  "requiere_2fa" BOOLEAN DEFAULT FALSE,
  "secreto_2fa" VARCHAR(255),
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ultimo_acceso" TIMESTAMP,
  "id_empleado" INTEGER,
  "id_cliente" INTEGER
);

-- Tabla de tokens refresh JWT
CREATE TABLE "tokens_refresh" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "token" VARCHAR(500) UNIQUE NOT NULL,
  "fecha_expiracion" TIMESTAMP NOT NULL,
  "revocado" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Links temporales para que evaluados carguen su hoja de vida (expira 36h)
CREATE TABLE "links_candidato" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" INTEGER NOT NULL,
  "token" VARCHAR(200) UNIQUE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "fecha_expiracion" TIMESTAMP NOT NULL,
  "usado" BOOLEAN DEFAULT FALSE NOT NULL
);

-- Historial de cambios de estado del semáforo de servicio
CREATE TABLE "historial_estados_servicio" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_servicio" INTEGER NOT NULL,
  "estado_anterior" VARCHAR(40),
  "estado_nuevo" VARCHAR(40) NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "fecha_cambio" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "observacion" TEXT
);

-- Notificaciones internas para usuarios del sistema
CREATE TABLE "notificaciones" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "titulo" VARCHAR(200) NOT NULL,
  "mensaje" TEXT NOT NULL,
  "leida" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "fecha_lectura" TIMESTAMP,
  "referencia_tipo" VARCHAR(50),
  "referencia_id" BIGINT
);

-- Hoja de vida del evaluado: la llena el propio candidato vía link temporal (36h).
-- Cuelga de "candidatos" (no de un servicio puntual) para que los datos se reutilicen
-- si en el futuro otro cliente vuelve a pedir un servicio para la misma persona.
CREATE TABLE "hoja_vida_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_candidato" BIGINT NOT NULL UNIQUE,
  "autorizacion_datos" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_autorizacion" TIMESTAMP,
  "completado" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_completado" TIMESTAMP,
  "progreso_porcentaje" INTEGER DEFAULT 0,
  "fecha_nacimiento" DATE,
  "lugar_nacimiento" VARCHAR(200),
  "estado_civil" VARCHAR(50),
  "nivel_educativo" VARCHAR(50),
  "direccion" TEXT,
  "barrio" VARCHAR(100),
  "estrato" VARCHAR(1),
  "email" VARCHAR(150),
  "celular" VARCHAR(20)
);

-- Educación del evaluado (múltiples registros)
CREATE TABLE "educacion_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "nivel" VARCHAR(50),
  "institucion" VARCHAR(200) NOT NULL,
  "titulo" VARCHAR(200),
  "fecha_inicio" DATE,
  "fecha_fin" DATE,
  "en_curso" BOOLEAN DEFAULT FALSE,
  "ciudad" VARCHAR(150)
);

-- Experiencia laboral del evaluado (múltiples registros)
CREATE TABLE "experiencia_laboral_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "empresa" VARCHAR(200) NOT NULL,
  "cargo" VARCHAR(150) NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE,
  "labora_actualmente" BOOLEAN DEFAULT FALSE,
  "ciudad" VARCHAR(150),
  "telefono_empresa" VARCHAR(20),
  "motivo_retiro" TEXT,
  "nombre_jefe" VARCHAR(150),
  "cargo_jefe" VARCHAR(100)
);

-- Períodos de inactividad calculados automáticamente
CREATE TABLE "inactividad_laboral_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE NOT NULL,
  "dias_inactivo" INTEGER NOT NULL,
  "justificacion" TEXT,
  "requiere_cuestionario" BOOLEAN DEFAULT FALSE NOT NULL
);

-- Referencias personales del evaluado
CREATE TABLE "referencia_personal_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "nombre" VARCHAR(150) NOT NULL,
  "parentesco" VARCHAR(50),
  "telefono" VARCHAR(20),
  "tiempo_conocimiento" VARCHAR(100)
);

-- Documentos adjuntos del evaluado
CREATE TABLE "documento_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "tipo_documento" VARCHAR(100) NOT NULL,
  "nombre_archivo" VARCHAR(255) NOT NULL,
  "ruta_archivo" VARCHAR(500),
  "fecha_carga" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX ON "usuarios" ("email");
CREATE INDEX ON "usuarios" ("rol");
CREATE INDEX ON "usuarios" ("activo");
CREATE INDEX ON "tokens_refresh" ("id_usuario");
CREATE UNIQUE INDEX ON "tokens_refresh" ("token");
CREATE INDEX ON "links_candidato" ("id_servicio");
CREATE UNIQUE INDEX ON "links_candidato" ("token");
CREATE INDEX ON "historial_estados_servicio" ("id_servicio");
CREATE INDEX ON "historial_estados_servicio" ("id_usuario");
CREATE INDEX ON "historial_estados_servicio" ("fecha_cambio");
CREATE INDEX ON "notificaciones" ("id_usuario");
CREATE INDEX ON "notificaciones" ("leida");
CREATE INDEX ON "experiencia_laboral_evaluado" ("id_hoja_vida");

-- Foreign keys
ALTER TABLE "tokens_refresh" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "links_candidato" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_estados_servicio" ADD FOREIGN KEY ("id_servicio") REFERENCES "servicios" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_estados_servicio" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notificaciones" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "servicios" ADD FOREIGN KEY ("id_usuario_solicita") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "hoja_vida_evaluado" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidatos" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "educacion_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "experiencia_laboral_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "inactividad_laboral_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "referencia_personal_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "documento_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
