CREATE TABLE "catalogo_servicios" (
  "id_catalogo"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre"       VARCHAR(150) NOT NULL,
  "descripcion"  TEXT,
  "categoria"    VARCHAR(40)  NOT NULL,
  "precio_base"  DECIMAL(12,2),
  "activo"       BOOLEAN DEFAULT TRUE NOT NULL,
  "orden"        INTEGER DEFAULT 0
);

CREATE INDEX ON "catalogo_servicios" ("categoria");
CREATE INDEX ON "catalogo_servicios" ("activo");
