-- Solicitudes de servicio (cliente solicita servicios para un evaluado)
CREATE TABLE "solicitudes" (
  "id_solicitud" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" INTEGER NOT NULL,
  "id_candidato" BIGINT,
  "cedula_evaluado" VARCHAR(20) NOT NULL,
  "nombres_evaluado" VARCHAR(200) NOT NULL,
  "apellidos_evaluado" VARCHAR(200) NOT NULL,
  "celular_evaluado" VARCHAR(20),
  "email_evaluado" VARCHAR(150),
  "ciudad_evaluado" VARCHAR(150),
  "cargo" VARCHAR(150),
  "notas" TEXT,
  "estado" VARCHAR(40) DEFAULT 'PENDIENTE',
  "fecha_solicitud" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "fecha_entrega_estimada" DATE,
  "id_usuario_solicita" BIGINT NOT NULL
);

-- Servicios del catálogo incluidos en cada solicitud
CREATE TABLE "solicitud_servicios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_solicitud" BIGINT NOT NULL,
  "id_catalogo" INTEGER NOT NULL,
  "estado" VARCHAR(40) DEFAULT 'PENDIENTE'
);

-- Historial de cambios de estado por solicitud
CREATE TABLE "historial_solicitudes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_solicitud" BIGINT NOT NULL,
  "estado_anterior" VARCHAR(40),
  "estado_nuevo" VARCHAR(40) NOT NULL,
  "id_usuario" BIGINT NOT NULL,
  "fecha_cambio" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "observacion" TEXT
);

-- Hoja de vida del evaluado (vinculada a la solicitud)
CREATE TABLE "hoja_vida_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_solicitud" BIGINT NOT NULL UNIQUE,
  "autorizacion_datos" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_autorizacion" TIMESTAMP,
  "completado" BOOLEAN DEFAULT FALSE NOT NULL,
  "fecha_completado" TIMESTAMP,
  "progreso_porcentaje" INTEGER DEFAULT 0,
  "fecha_nacimiento" DATE,
  "lugar_nacimiento" VARCHAR(200),
  "estado_civil" VARCHAR(50),
  "nivel_educativo" VARCHAR(50),
  "direccion" TEXT,
  "barrio" VARCHAR(100),
  "estrato" VARCHAR(1),
  "email" VARCHAR(150),
  "celular" VARCHAR(20)
);

-- Educación del evaluado (múltiples registros)
CREATE TABLE "educacion_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "nivel" VARCHAR(50),
  "institucion" VARCHAR(200) NOT NULL,
  "titulo" VARCHAR(200),
  "fecha_inicio" DATE,
  "fecha_fin" DATE,
  "en_curso" BOOLEAN DEFAULT FALSE,
  "ciudad" VARCHAR(150)
);

-- Experiencia laboral del evaluado (múltiples registros)
CREATE TABLE "experiencia_laboral_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "empresa" VARCHAR(200) NOT NULL,
  "cargo" VARCHAR(150) NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE,
  "labora_actualmente" BOOLEAN DEFAULT FALSE,
  "ciudad" VARCHAR(150),
  "telefono_empresa" VARCHAR(20),
  "motivo_retiro" TEXT,
  "nombre_jefe" VARCHAR(150),
  "cargo_jefe" VARCHAR(100)
);

-- Períodos de inactividad calculados automáticamente
CREATE TABLE "inactividad_laboral_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_fin" DATE NOT NULL,
  "dias_inactivo" INTEGER NOT NULL,
  "justificacion" TEXT,
  "requiere_cuestionario" BOOLEAN DEFAULT FALSE NOT NULL
);

-- Referencias personales del evaluado
CREATE TABLE "referencia_personal_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "nombre" VARCHAR(150) NOT NULL,
  "parentesco" VARCHAR(50),
  "telefono" VARCHAR(20),
  "tiempo_conocimiento" VARCHAR(100)
);

-- Documentos adjuntos del evaluado
CREATE TABLE "documento_evaluado" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_hoja_vida" BIGINT NOT NULL,
  "tipo_documento" VARCHAR(100) NOT NULL,
  "nombre_archivo" VARCHAR(255) NOT NULL,
  "ruta_archivo" VARCHAR(500),
  "fecha_carga" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Relacionar links_candidato con solicitudes (id_servicio ahora opcional)
ALTER TABLE "links_candidato" ALTER COLUMN "id_servicio" DROP NOT NULL;
ALTER TABLE "links_candidato" ADD COLUMN "id_solicitud" BIGINT;

-- Días hábiles de entrega por servicio del catálogo
ALTER TABLE "catalogo_servicios" ADD COLUMN "dias_habiles_entrega" INTEGER DEFAULT 5;

-- Índices
CREATE INDEX ON "solicitudes" ("id_cliente");
CREATE INDEX ON "solicitudes" ("cedula_evaluado");
CREATE INDEX ON "solicitudes" ("estado");
CREATE INDEX ON "solicitudes" ("fecha_solicitud");
CREATE INDEX ON "solicitud_servicios" ("id_solicitud");
CREATE INDEX ON "historial_solicitudes" ("id_solicitud");
CREATE INDEX ON "hoja_vida_evaluado" ("id_solicitud");
CREATE INDEX ON "experiencia_laboral_evaluado" ("id_hoja_vida");

-- Foreign keys
ALTER TABLE "solicitudes" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "solicitudes" ADD FOREIGN KEY ("id_candidato") REFERENCES "candidatos" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "solicitudes" ADD FOREIGN KEY ("id_usuario_solicita") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "solicitud_servicios" ADD FOREIGN KEY ("id_solicitud") REFERENCES "solicitudes" ("id_solicitud") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "solicitud_servicios" ADD FOREIGN KEY ("id_catalogo") REFERENCES "catalogo_servicios" ("id_catalogo") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_solicitudes" ADD FOREIGN KEY ("id_solicitud") REFERENCES "solicitudes" ("id_solicitud") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "historial_solicitudes" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "hoja_vida_evaluado" ADD FOREIGN KEY ("id_solicitud") REFERENCES "solicitudes" ("id_solicitud") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "educacion_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "experiencia_laboral_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "inactividad_laboral_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "referencia_personal_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "documento_evaluado" ADD FOREIGN KEY ("id_hoja_vida") REFERENCES "hoja_vida_evaluado" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "links_candidato" ADD FOREIGN KEY ("id_solicitud") REFERENCES "solicitudes" ("id_solicitud") DEFERRABLE INITIALLY IMMEDIATE;
